[tool.black]
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.plone-code-analysis]
checkers = ["black", "flake8", "isort", "pyroma", "zpretty"]
formatters = ["black", "isort", "zpretty"]
paths = "src"
paths_flake8 = "src"

