[tool.black]
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.flakeheaven]
format="grouped"
max_line_length=88
show_source=true
max-complexity=25

[tool.flakeheaven.plugins]
pycodestyle = ["+*"]
pyflakes = ["+*"]
"flake8-*" = ["+*"]

[tool.codespell]
ignore-words-list = "discreet,succeded"
skip = "*.po,"
##
# Add extra configuration options in .meta.toml:
#  [pyproject]
#  codespell_ignores = "foo,bar"
#  codespell_skip = "*.po,*.map,package-lock.json"
##

[tool.plone-code-analysis]
checkers = ["black", "flake8", "isort", "pyroma", "zpretty"]
formatters = ["black", "isort", "zpretty"]
paths = "."
paths_pyroma = "."
paths_black = "."
paths_flake8 = "."
paths_isort = "."
# paths_pyroma = "."
paths_zpretty = "."

