name: Testing

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
        plone:
          - "6.0.6"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          pip install -e ".[test]" --use-deprecated legacy-resolver

      - name: Run tests
        run: |
          pytest --disable-warnings